# permissions for end users to edit compoundainims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: compoundai-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: compoundainim-editor-role
rules:
- apiGroups:
  - nvidia.com
  resources:
  - compoundainims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - compoundainims/status
  verbs:
  - get
