# cargo-deny plugin for linting dependencies
# https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "OpenSSL",
    "Unicode-3.0",
    "BSL-1.0"
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]