default:
  tags:
    - nemollm-common
  # sane default, every job can be cancelled by some other event (override in jobs that can't be interrupted; i.e. deployment)
  interruptible: true

variables:
  CI_REGISTRY_IMAGE: nvcr.io/nvidian/nemo-llm
  SERVICE_NAME: compoundai-api-server

workflow:
  rules:
    # no branch pipeline while MR is open against same branch
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # tag pipelines allowed
    - if: $CI_COMMIT_TAG
    # protected branch and tag pipelines allowed
    - if: $CI_COMMIT_REF_PROTECTED
    # schedule pipelines allowed
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - compile
  - build
  - publish

build:
  stage: compile
  image: golang:1.23
  script:
    - echo "Building the Golang Gin project..."
    - go mod tidy # Ensure dependencies are downloaded and tidy
    - go build -o main ./api
  only:
    - merge_requests

include:
  - component: gitlab-master.nvidia.com/dl/ai-services/gitlab-components/nemo-artifact/build-docker@5.2
    inputs:
      image_uri: ${CI_REGISTRY_IMAGE}/${SERVICE_NAME}
  - component: gitlab-master.nvidia.com/dl/ai-services/gitlab-components/nemo-artifact/image-publish@5.2
    inputs:
      local_image: ${CI_REGISTRY_IMAGE}/${SERVICE_NAME}
      remote_image_dest: nvcr.io/nvidian/nemo-llm/${SERVICE_NAME}
      rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: on_success
        variables:
          REMOTE_TAG: ${CI_COMMIT_SHA}
      - if: $CI_COMMIT_TAG == null
        when: manual
        allow_failure: true
        variables:
          REMOTE_TAG: ${CI_COMMIT_SHA}
      - if: $CI_COMMIT_TAG != null
        when: always
        variables:
          REMOTE_TAG: ${CI_COMMIT_TAG}