# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Rust pre-merge checks

on:
  # Always run this workflow when commits are pushed to main.
  push:
    branches:
    - main
    - anants/*

  # Run this workflow on pull requests targeting main but only if files in runtime/rust change.
  pull_request:
    branches:
    - main
    paths:
    - 'runtime/rust/**'
    - 'llm/rust/**'
    - 'applications/llm/bin/tio/**'
    - '**.rs'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - '.github/workflows/rust-pre-merge-checks.yml'

jobs:
  filter:
    name: Rust Filter Checks
    runs-on: ubuntu-latest
    outputs:
      runtime: ${{ steps.filter.outputs.runtime }}
      tio: ${{ steps.filter.outputs.tio }}
      llm: ${{ steps.filter.outputs.llm }}
    steps:
    - uses: actions/checkout@v4
    - name: Detect changes in Rust projects
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          runtime:
            - 'runtime/rust/**'
          tio:
            - 'applications/llm/bin/tio/**'
          llm:
            - 'llm/rust/**'

  rust-checks:
    needs: filter
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['runtime', 'tio', 'llm']
    if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
    steps:
    - name: Set working directory
      run: |
        if [ "${{ matrix.project }}" = "runtime" ]; then
          echo "WORK_DIR=runtime/rust" >> $GITHUB_ENV
        elif [ "${{ matrix.project }}" = "tio" ]; then
          echo "WORK_DIR=applications/llm/bin/tio" >> $GITHUB_ENV
        else
          echo "WORK_DIR=llm/rust" >> $GITHUB_ENV
        fi    
    - uses: actions/checkout@v4
    - name: Cache Cargo Registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ github.head_ref || github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache Cargo Tools
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-tools-${{ github.head_ref || github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Set up system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler
        rustup component add rustfmt clippy
    - name: Run Cargo Check
      working-directory: ${{ env.WORK_DIR }}
      run: cargo check --locked
    - name: Verify Code Formatting
      working-directory: ${{ env.WORK_DIR }}
      run: cargo fmt -- --check
    - name: Run Clippy Checks
      working-directory: ${{ env.WORK_DIR }}
      run: cargo clippy --no-deps --all-targets -- -D warnings
    - name: Run Unit Tests
      working-directory: ${{ env.WORK_DIR }}
      run: cargo test --locked --all-targets
